# Generated by Django 5.1.4 on 2026-01-09 22:55

import core.models.tenant
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único (UUID) do tenant', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome completo da empresa/loja', max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(db_index=True, help_text='CNPJ da empresa (será validado automaticamente)', max_length=18, unique=True, validators=[core.models.tenant.validate_cnpj_field], verbose_name='CNPJ')),
                ('plan', models.CharField(choices=[('BASIC', 'Básico'), ('PRO', 'Profissional')], default='BASIC', help_text='Plano de assinatura do tenant', max_length=10, verbose_name='Plano')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('TRIAL', 'Período de Teste')], default='ACTIVE', help_text='Status atual do tenant no sistema', max_length=10, verbose_name='Status')),
                ('billing_day_weekly', models.IntegerField(default=1, help_text='0=Domingo, 1=Segunda, 2=Terça, ..., 6=Sábado', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Dia da Semana para Faturamento Semanal')),
                ('billing_day_monthly', models.IntegerField(default=5, help_text='Dia do mês (1-31) para solicitação de faturamento mensal', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do Mês para Faturamento Mensal')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o tenant foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do tenant', verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['cnpj'], name='core_tenant_cnpj_dc1d24_idx'), models.Index(fields=['status'], name='core_tenant_status_55a303_idx'), models.Index(fields=['plan'], name='core_tenant_plan_afa62f_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único (UUID) do usuário', primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email do usuário (usado como username)', max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('ADMIN_MASTER', 'Administrador Master'), ('GESTOR', 'Gestor'), ('OPERADOR', 'Operador')], default='OPERADOR', help_text='Função do usuário no sistema', max_length=15, verbose_name='Role')),
                ('whatsapp_number', models.CharField(blank=True, db_index=True, help_text='Número do WhatsApp no formato internacional (ex: 5541999999999)', max_length=20, null=True, unique=True, verbose_name='Número WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o usuário foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do usuário', verbose_name='Data de Atualização')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(blank=True, help_text='Loja/Empresa do usuário (None apenas para ADMIN_MASTER)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['email'],
                'indexes': [models.Index(fields=['email'], name='core_user_email_38052c_idx'), models.Index(fields=['tenant', 'role'], name='core_user_tenant__469ef1_idx'), models.Index(fields=['whatsapp_number'], name='core_user_whatsap_54673c_idx')],
            },
        ),
    ]
