# Generated by Django 5.1.4 on 2026-01-09 23:07

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único (UUID) do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('name', models.CharField(db_index=True, help_text='Nome da categoria (ex: Despesa Fixa, Estoque)', max_length=255, verbose_name='Nome')),
                ('type', models.CharField(choices=[('FIXA', 'Despesa Fixa'), ('VARIAVEL', 'Despesa Variável'), ('INVESTIMENTO', 'Investimento'), ('ESTOQUE', 'Estoque')], help_text='Tipo de categoria para classificação financeira', max_length=20, verbose_name='Tipo')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant proprietário (None para categorias globais do Glossário)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único (UUID) do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('name', models.CharField(db_index=True, help_text='Nome da subcategoria (ex: Aluguel, Luz, Água)', max_length=255, verbose_name='Nome')),
                ('category', models.ForeignKey(help_text='Categoria pai desta subcategoria', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category', verbose_name='Categoria')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant proprietário (None para subcategorias globais do Glossário)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearnedRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único (UUID) do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('keyword', models.CharField(db_index=True, help_text='Palavra-chave ou nome de fornecedor para matching automático', max_length=255, verbose_name='Palavra-chave')),
                ('hit_count', models.IntegerField(default=0, help_text='Número de vezes que esta regra foi aplicada com sucesso', verbose_name='Contador de Acertos')),
                ('active', models.BooleanField(default=True, help_text='Indica se a regra está ativa (pode ser desativada se não funcionar bem)', verbose_name='Ativa')),
                ('category', models.ForeignKey(help_text='Categoria sugerida automaticamente', on_delete=django.db.models.deletion.CASCADE, related_name='learned_rules', to='core.category', verbose_name='Categoria')),
                ('tenant', models.ForeignKey(help_text='Loja/Empresa proprietária deste registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='Tenant')),
                ('subcategory', models.ForeignKey(help_text='Subcategoria sugerida automaticamente', on_delete=django.db.models.deletion.CASCADE, related_name='learned_rules', to='core.subcategory', verbose_name='Subcategoria')),
            ],
            options={
                'verbose_name': 'Regra Aprendida',
                'verbose_name_plural': 'Regras Aprendidas',
                'ordering': ['-hit_count', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único (UUID) do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('description', models.TextField(help_text='Descrição detalhada da transação', verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor total bruto da transação', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Bruto')),
                ('competence_date', models.DateField(help_text='Data de competência (mês/ano) para DRE - Quando ocorreu o fato gerador', verbose_name='Data de Competência')),
                ('supplier', models.CharField(blank=True, db_index=True, help_text='Nome do fornecedor/prestador de serviço', max_length=255, null=True, verbose_name='Fornecedor')),
                ('category', models.ForeignKey(help_text='Categoria da transação', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.category', verbose_name='Categoria')),
                ('subcategory', models.ForeignKey(help_text='Subcategoria detalhada da transação', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.subcategory', verbose_name='Subcategoria')),
                ('tenant', models.ForeignKey(help_text='Loja/Empresa proprietária deste registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-competence_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único (UUID) do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('raw_text', models.TextField(help_text='Texto original da mensagem recebida (WhatsApp)', verbose_name='Texto Original')),
                ('extracted_json', models.JSONField(help_text='Dados estruturados extraídos pela IA (formato JSON)', verbose_name='JSON Extraído')),
                ('expires_at', models.DateTimeField(help_text='Data e hora de expiração desta sessão (para limpeza automática)', verbose_name='Expira em')),
                ('confirmed', models.BooleanField(default=False, help_text='Indica se a sessão foi confirmada pelo usuário', verbose_name='Confirmado')),
                ('tenant', models.ForeignKey(help_text='Loja/Empresa proprietária deste registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='Tenant')),
                ('confirmed_transaction', models.ForeignKey(blank=True, help_text='Transação criada após confirmação (se houver)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsing_sessions', to='core.transaction', verbose_name='Transação Confirmada')),
            ],
            options={
                'verbose_name': 'Sessão de Parsing',
                'verbose_name_plural': 'Sessões de Parsing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único (UUID) do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('due_date', models.DateField(help_text='Data em que a parcela vence (caixa esperado)', verbose_name='Data de Vencimento')),
                ('payment_date', models.DateField(blank=True, help_text='Data em que a parcela foi paga (caixa realizado)', null=True, verbose_name='Data de Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor líquido da parcela (sem multas/juros)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Líquido')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de multas e juros pagos nesta parcela', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Multas e Juros')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', help_text='Status atual da parcela', max_length=10, verbose_name='Status')),
                ('tenant', models.ForeignKey(help_text='Loja/Empresa proprietária deste registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='Tenant')),
                ('transaction', models.ForeignKey(help_text='Transação à qual esta parcela pertence', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='core.transaction', verbose_name='Transação')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'type'], name='core_catego_tenant__5e0919_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['type', 'name'], name='core_catego_type_5651a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'name'), name='unique_category_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('name',), name='unique_global_category'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['tenant', 'category'], name='core_subcat_tenant__c86beb_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'name'], name='core_subcat_categor_93725f_idx'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'category', 'name'), name='unique_subcategory_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('category', 'name'), name='unique_global_subcategory'),
        ),
        migrations.AddIndex(
            model_name='learnedrule',
            index=models.Index(fields=['tenant', 'keyword'], name='core_learne_tenant__24df83_idx'),
        ),
        migrations.AddIndex(
            model_name='learnedrule',
            index=models.Index(fields=['tenant', 'active'], name='core_learne_tenant__1c7345_idx'),
        ),
        migrations.AddIndex(
            model_name='learnedrule',
            index=models.Index(fields=['keyword', 'active'], name='core_learne_keyword_f917e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='learnedrule',
            constraint=models.UniqueConstraint(fields=('tenant', 'keyword'), name='unique_rule_per_tenant_keyword'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', '-competence_date'], name='core_transa_tenant__b7adf3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'category'], name='core_transa_tenant__6d555d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'subcategory'], name='core_transa_tenant__49ae73_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['competence_date'], name='core_transa_compete_62b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='parsingsession',
            index=models.Index(fields=['tenant', '-created_at'], name='core_parsin_tenant__0bc533_idx'),
        ),
        migrations.AddIndex(
            model_name='parsingsession',
            index=models.Index(fields=['tenant', 'confirmed'], name='core_parsin_tenant__6eab0b_idx'),
        ),
        migrations.AddIndex(
            model_name='parsingsession',
            index=models.Index(fields=['expires_at'], name='core_parsin_expires_56fa2e_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['tenant', 'due_date'], name='core_instal_tenant__b31b47_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['tenant', 'payment_date'], name='core_instal_tenant__fec2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['tenant', 'status'], name='core_instal_tenant__b1f362_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['due_date', 'status'], name='core_instal_due_dat_e84de1_idx'),
        ),
    ]
