# Generated by Django 5.1.4 on 2026-01-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_subcategory_learnedrule_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parsingsession',
            name='core_parsin_tenant__6eab0b_idx',
        ),
        migrations.RemoveField(
            model_name='parsingsession',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='parsingsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('CANCELED', 'Cancelado')], default='PENDING', help_text='Status atual da sessão de parsing', max_length=10, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='parsingsession',
            index=models.Index(fields=['tenant', 'status'], name='core_parsin_tenant__297114_idx'),
        ),
    ]
