# Generated by Django 5.1.4 on 2026-01-09 23:51

import core.models.finance
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_parsingsession_core_parsin_tenant__6eab0b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingsession',
            name='audio_url',
            field=models.URLField(blank=True, help_text='URL do áudio (mensagem de voz) recebido via WhatsApp', max_length=500, null=True, verbose_name='URL do Áudio'),
        ),
        migrations.AddField(
            model_name='parsingsession',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Arquivo de imagem armazenado localmente em media/tenants/{tenant_id}/invoices/', null=True, upload_to=core.models.finance.invoice_upload_path, verbose_name='Arquivo de Imagem'),
        ),
        migrations.AddField(
            model_name='parsingsession',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL da imagem (comprovante/nota fiscal) recebida via WhatsApp', max_length=500, null=True, verbose_name='URL da Imagem'),
        ),
        migrations.AlterField(
            model_name='parsingsession',
            name='raw_text',
            field=models.TextField(help_text='Texto original da mensagem recebida (WhatsApp) ou transcrito de áudio', verbose_name='Texto Original'),
        ),
    ]
