# Generated by Django 5.2.10 on 2026-01-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_image_audio_to_parsing_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='evolution_instance_name',
            field=models.CharField(blank=True, help_text='Nome da instância do WhatsApp configurada na Evolution API (usado para status de conexão)', max_length=255, null=True, verbose_name='Nome da Instância Evolution API'),
        ),
    ]
