# Generated by Django 5.2.10 on 2026-01-20 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_tenant_evolution_instance_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='core_user_tenant__469ef1_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='Lojas/Empresas às quais o usuário tem acesso (vazio apenas para ADMIN_MASTER)', related_name='users', to='core.tenant', verbose_name='Lojas/Empresas'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('PLUS', 'Plus'), ('PRO', 'Pro')], default='STARTER', help_text='Plano de assinatura do tenant (Starter=1 instância, Plus=2, Pro=5)', max_length=10, verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Campo legado - será removido após migração. Use tenants (ManyToMany) ao invés.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_users', to='core.tenant', verbose_name='Tenant (Legado)'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='core_user_role_73872d_idx'),
        ),
    ]
