# Generated by Django 5.2.10 on 2026-01-20 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_migrate_legacy_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cash_date',
            field=models.DateField(blank=True, help_text='Data em que o dinheiro entrou/saiu (apenas para receitas, se diferente da competência)', null=True, verbose_name='Data de Caixa'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], default='DESPESA', help_text='Se é uma receita ou despesa', max_length=10, verbose_name='Tipo de Transação'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoria da transação (apenas para despesas)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Subcategoria detalhada da transação (apenas para despesas)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.subcategory', verbose_name='Subcategoria'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='supplier',
            field=models.CharField(blank=True, db_index=True, help_text='Nome do fornecedor/prestador de serviço (apenas para despesas)', max_length=255, null=True, verbose_name='Fornecedor'),
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único (UUID) do registro', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('name', models.CharField(db_index=True, help_text='Nome do canal de venda (ex: iFood, Balcão, Delivery Próprio)', max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição adicional do canal de venda', null=True, verbose_name='Descrição')),
                ('active', models.BooleanField(default=True, help_text='Se o canal está ativo e pode ser usado', verbose_name='Ativo')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant proprietário (None para canais globais)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_channels', to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Canal de Venda',
                'verbose_name_plural': 'Canais de Venda',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='sales_channel',
            field=models.ForeignKey(blank=True, help_text='Canal de venda da receita (apenas para receitas)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.saleschannel', verbose_name='Canal de Venda'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'transaction_type'], name='core_transa_tenant__1bcf7b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'sales_channel'], name='core_transa_tenant__362b89_idx'),
        ),
        migrations.AddIndex(
            model_name='saleschannel',
            index=models.Index(fields=['tenant', 'active'], name='core_salesc_tenant__4fb8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='saleschannel',
            index=models.Index(fields=['name'], name='core_salesc_name_5506f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleschannel',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'name'), name='unique_sales_channel_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='saleschannel',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('name',), name='unique_global_sales_channel'),
        ),
    ]
