# Generated by Django 5.2.10 on 2026-01-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_sales_channel_and_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='competence_date_end',
            field=models.DateField(blank=True, help_text='Data de fim do período de competência (apenas para receitas). Se não informada, considera apenas a data de início.', null=True, verbose_name='Data de Fim do Período'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='competence_date',
            field=models.DateField(help_text='Data de competência (mês/ano) para DRE - Quando ocorreu o fato gerador. Para receitas, é a data de início do período.', verbose_name='Data de Competência'),
        ),
    ]
