# Generated by Django 5.2.10 on 2026-01-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transaction_competence_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição detalhada da transação', null=True, verbose_name='Descrição'),
        ),
    ]
