# Generated by Django 5.2.10 on 2026-01-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_make_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(default='', help_text='Cidade onde o restaurante está localizado (necessário para integrações de clima e eventos)', max_length=255, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='neighborhood',
            field=models.CharField(default='', help_text='Bairro onde o restaurante está localizado (necessário para integrações de clima e eventos)', max_length=255, verbose_name='Bairro'),
        ),
    ]
