# Generated by Django 5.2.10 on 2026-01-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tenant_city_tenant_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, help_text='Cidade onde o restaurante está localizado (necessário para integrações de clima e eventos)', max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='neighborhood',
            field=models.CharField(blank=True, help_text='Bairro onde o restaurante está localizado (necessário para integrações de clima e eventos)', max_length=255, null=True, verbose_name='Bairro'),
        ),
    ]
